# Generated by Django 4.2.3 on 2023-07-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reportedurl_reported_date_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedurl',
            name='reported_date',
        ),
    ]
