# Generated by Django 4.2.3 on 2023-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedurl',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
